### ISSUE TITLE
Can not send inivitation by email.

### ISSUE THREAD

**Issue by BruceWind** [railwayapp-starters/ghost#16]
I click **resend** button for sending an email. 
![1690963918040](https://github.com/railwayapp-templates/ghost/assets/6711309/8fff1ec1-671e-4f83-8043-0e7f3efe6f71)

But  I got error of response. from url: _https://[subdomain].maindomain.com/ghost/api/admin/invites/_

```
{
    "errors": [
        {
            "message": "Error sending email!",
            "context": "Error sending email: Failed to send email. Reason: Invalid login: 535 Authentication failed. Please check your email settings and resend the invitation.",
            "type": "EmailError",
            "details": null,
            "property": null,
            "help": "Please see https://ghost.org/docs/config/#mail for instructions on configuring email.",
            "code": "EAUTH",
            "id": "08a20af0-310c-11ee-9fb1-010f428337f9"
        }
    ]
}
```

I use **mailgun** in setting. I think all set is ok, I had use the mailgun **config(domain,key)** to send email in auth0 before this time.

**Comment by brody192** [comment]
can you please move to to a help thread on our discord? [discord.gg/railway](https://discord.gg/railway)

**Comment by BruceWind** [comment]
I had the intention to be in discord, but I reckon this issue is relate to ghost, not railway. So I decieded to come up to here.

**Comment by BruceWind** [comment]
sorry it looks like relate  to https://github.com/TryGhost/Ghost/issues/13353

**Comment by BruceWind** [comment]
It is my fault, I need to reset password in the dashboard of mailgun.
